//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBusiness.NewService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewService.INewService")]
    public interface INewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewService/GetEmployeesUsingDBWithConfig", ReplyAction="http://tempuri.org/INewService/GetEmployeesUsingDBWithConfigResponse")]
        System.Data.DataSet GetEmployeesUsingDBWithConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewService/GetEmployeesUsingDBWithConfig", ReplyAction="http://tempuri.org/INewService/GetEmployeesUsingDBWithConfigResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeesUsingDBWithConfigAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewServiceChannel : NewBusiness.NewService.INewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewServiceClient : System.ServiceModel.ClientBase<NewBusiness.NewService.INewService>, NewBusiness.NewService.INewService {
        
        public NewServiceClient() {
        }
        
        public NewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetEmployeesUsingDBWithConfig() {
            return base.Channel.GetEmployeesUsingDBWithConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeesUsingDBWithConfigAsync() {
            return base.Channel.GetEmployeesUsingDBWithConfigAsync();
        }
    }
}
